/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines AdoptionStatus
    /// </summary>
        public enum AdoptionStatus
    {
        /// <summary>
        /// Enum AdoptionPending for value: Adoption Pending
        /// </summary>
        
        AdoptionPending = Adoption Pending,
        /// <summary>
        /// Enum Available for value: Available
        /// </summary>
        
        Available = Available,
        /// <summary>
        /// Enum AvailablePendingSpayNeuter for value: Available Pending Spay/Neuter
        /// </summary>
        
        AvailablePendingSpayNeuter = Available Pending Spay/Neuter,
        /// <summary>
        /// Enum MedicalHold for value: Medical Hold
        /// </summary>
        
        MedicalHold = Medical Hold,
        /// <summary>
        /// Enum PendingIntakeTesting for value: Pending Intake Testing
        /// </summary>
        
        PendingIntakeTesting = Pending Intake Testing    }
}
