/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AvailabilityScheduleDateRange
    /// </summary>
    [DataContract]
        public partial class AvailabilityScheduleDateRange :  IEquatable<AvailabilityScheduleDateRange>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailabilityScheduleDateRange" /> class.
        /// </summary>
        /// <param name="begin">begin.</param>
        /// <param name="end">end.</param>
        public AvailabilityScheduleDateRange(AvailabilityScheduleDateRangeBegin begin = default(AvailabilityScheduleDateRangeBegin), AvailabilityScheduleDateRangeBegin end = default(AvailabilityScheduleDateRangeBegin))
        {
            this.Begin = begin;
            this.End = end;
        }
        
        /// <summary>
        /// Gets or Sets Begin
        /// </summary>
        [DataMember(Name="begin", EmitDefaultValue=false)]
        public AvailabilityScheduleDateRangeBegin Begin { get; set; }

        /// <summary>
        /// Gets or Sets End
        /// </summary>
        [DataMember(Name="end", EmitDefaultValue=false)]
        public AvailabilityScheduleDateRangeBegin End { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AvailabilityScheduleDateRange {\n");
            sb.Append("  Begin: ").Append(Begin).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AvailabilityScheduleDateRange);
        }

        /// <summary>
        /// Returns true if AvailabilityScheduleDateRange instances are equal
        /// </summary>
        /// <param name="input">Instance of AvailabilityScheduleDateRange to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AvailabilityScheduleDateRange input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Begin == input.Begin ||
                    (this.Begin != null &&
                    this.Begin.Equals(input.Begin))
                ) && 
                (
                    this.End == input.End ||
                    (this.End != null &&
                    this.End.Equals(input.End))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Begin != null)
                    hashCode = hashCode * 59 + this.Begin.GetHashCode();
                if (this.End != null)
                    hashCode = hashCode * 59 + this.End.GetHashCode();
                return hashCode;
            }
        }
    }
}
