/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines CatColors
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum CatColors
    {
        /// <summary>
        /// Enum White for value: White
        /// </summary>
        [EnumMember(Value = "White")]
        White = 0,
        /// <summary>
        /// Enum Black for value: Black
        /// </summary>
        [EnumMember(Value = "Black")]
        Black = 1,
        /// <summary>
        /// Enum BlackandWhite for value: Black and White
        /// </summary>
        [EnumMember(Value = "Black and White")]
        BlackandWhite = 2,
        /// <summary>
        /// Enum OrangeTabby for value: Orange Tabby
        /// </summary>
        [EnumMember(Value = "Orange Tabby")]
        OrangeTabby = 3,
        /// <summary>
        /// Enum OrangeandWhite for value: Orange and White
        /// </summary>
        [EnumMember(Value = "Orange and White")]
        OrangeandWhite = 4,
        /// <summary>
        /// Enum Brown for value: Brown
        /// </summary>
        [EnumMember(Value = "Brown")]
        Brown = 5,
        /// <summary>
        /// Enum BrownTabby for value: Brown Tabby
        /// </summary>
        [EnumMember(Value = "Brown Tabby")]
        BrownTabby = 6,
        /// <summary>
        /// Enum BrownandWhite for value: Brown and White
        /// </summary>
        [EnumMember(Value = "Brown and White")]
        BrownandWhite = 7,
        /// <summary>
        /// Enum Gray for value: Gray
        /// </summary>
        [EnumMember(Value = "Gray")]
        Gray = 8,
        /// <summary>
        /// Enum GrayandWhite for value: Gray and White
        /// </summary>
        [EnumMember(Value = "Gray and White")]
        GrayandWhite = 9,
        /// <summary>
        /// Enum GrayTabby for value: Gray Tabby
        /// </summary>
        [EnumMember(Value = "Gray Tabby")]
        GrayTabby = 10,
        /// <summary>
        /// Enum Silver for value: Silver
        /// </summary>
        [EnumMember(Value = "Silver")]
        Silver = 11,
        /// <summary>
        /// Enum SilverandWhite for value: Silver and White
        /// </summary>
        [EnumMember(Value = "Silver and White")]
        SilverandWhite = 12,
        /// <summary>
        /// Enum SilverTabby for value: Silver Tabby
        /// </summary>
        [EnumMember(Value = "Silver Tabby")]
        SilverTabby = 13,
        /// <summary>
        /// Enum Buff for value: Buff
        /// </summary>
        [EnumMember(Value = "Buff")]
        Buff = 14,
        /// <summary>
        /// Enum BuffandWhite for value: Buff and White
        /// </summary>
        [EnumMember(Value = "Buff and White")]
        BuffandWhite = 15,
        /// <summary>
        /// Enum BuffTabby for value: Buff Tabby
        /// </summary>
        [EnumMember(Value = "Buff Tabby")]
        BuffTabby = 16,
        /// <summary>
        /// Enum SealPoint for value: Seal Point
        /// </summary>
        [EnumMember(Value = "Seal Point")]
        SealPoint = 17,
        /// <summary>
        /// Enum FlamePoint for value: Flame Point
        /// </summary>
        [EnumMember(Value = "Flame Point")]
        FlamePoint = 18,
        /// <summary>
        /// Enum LavendarLilacPoint for value: Lavendar/Lilac Point
        /// </summary>
        [EnumMember(Value = "Lavendar/Lilac Point")]
        LavendarLilacPoint = 19,
        /// <summary>
        /// Enum Snowshoe for value: Snowshoe
        /// </summary>
        [EnumMember(Value = "Snowshoe")]
        Snowshoe = 20,
        /// <summary>
        /// Enum Calico for value: Calico
        /// </summary>
        [EnumMember(Value = "Calico")]
        Calico = 21,
        /// <summary>
        /// Enum Tortie for value: Tortie
        /// </summary>
        [EnumMember(Value = "Tortie")]
        Tortie = 22,
        /// <summary>
        /// Enum DiluteCalico for value: Dilute Calico
        /// </summary>
        [EnumMember(Value = "Dilute Calico")]
        DiluteCalico = 23    }
}
