/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DayOfMonthSelect
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DayOfMonthSelect
    {
        /// <summary>
        /// Enum _1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        _1 = 0,
        /// <summary>
        /// Enum _2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        _2 = 1,
        /// <summary>
        /// Enum _3 for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        _3 = 2,
        /// <summary>
        /// Enum _4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        _4 = 3,
        /// <summary>
        /// Enum _5 for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        _5 = 4,
        /// <summary>
        /// Enum _6 for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        _6 = 5,
        /// <summary>
        /// Enum _7 for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        _7 = 6,
        /// <summary>
        /// Enum _8 for value: 8
        /// </summary>
        [EnumMember(Value = "8")]
        _8 = 7,
        /// <summary>
        /// Enum _9 for value: 9
        /// </summary>
        [EnumMember(Value = "9")]
        _9 = 8,
        /// <summary>
        /// Enum _10 for value: 10
        /// </summary>
        [EnumMember(Value = "10")]
        _10 = 9,
        /// <summary>
        /// Enum _11 for value: 11
        /// </summary>
        [EnumMember(Value = "11")]
        _11 = 10,
        /// <summary>
        /// Enum _12 for value: 12
        /// </summary>
        [EnumMember(Value = "12")]
        _12 = 11,
        /// <summary>
        /// Enum _13 for value: 13
        /// </summary>
        [EnumMember(Value = "13")]
        _13 = 12,
        /// <summary>
        /// Enum _14 for value: 14
        /// </summary>
        [EnumMember(Value = "14")]
        _14 = 13,
        /// <summary>
        /// Enum _15 for value: 15
        /// </summary>
        [EnumMember(Value = "15")]
        _15 = 14,
        /// <summary>
        /// Enum _16 for value: 16
        /// </summary>
        [EnumMember(Value = "16")]
        _16 = 15,
        /// <summary>
        /// Enum _17 for value: 17
        /// </summary>
        [EnumMember(Value = "17")]
        _17 = 16,
        /// <summary>
        /// Enum _18 for value: 18
        /// </summary>
        [EnumMember(Value = "18")]
        _18 = 17,
        /// <summary>
        /// Enum _19 for value: 19
        /// </summary>
        [EnumMember(Value = "19")]
        _19 = 18,
        /// <summary>
        /// Enum _20 for value: 20
        /// </summary>
        [EnumMember(Value = "20")]
        _20 = 19,
        /// <summary>
        /// Enum _21 for value: 21
        /// </summary>
        [EnumMember(Value = "21")]
        _21 = 20,
        /// <summary>
        /// Enum _22 for value: 22
        /// </summary>
        [EnumMember(Value = "22")]
        _22 = 21,
        /// <summary>
        /// Enum _23 for value: 23
        /// </summary>
        [EnumMember(Value = "23")]
        _23 = 22,
        /// <summary>
        /// Enum _24 for value: 24
        /// </summary>
        [EnumMember(Value = "24")]
        _24 = 23,
        /// <summary>
        /// Enum _25 for value: 25
        /// </summary>
        [EnumMember(Value = "25")]
        _25 = 24,
        /// <summary>
        /// Enum _26 for value: 26
        /// </summary>
        [EnumMember(Value = "26")]
        _26 = 25,
        /// <summary>
        /// Enum _27 for value: 27
        /// </summary>
        [EnumMember(Value = "27")]
        _27 = 26,
        /// <summary>
        /// Enum _28 for value: 28
        /// </summary>
        [EnumMember(Value = "28")]
        _28 = 27,
        /// <summary>
        /// Enum _29 for value: 29
        /// </summary>
        [EnumMember(Value = "29")]
        _29 = 28,
        /// <summary>
        /// Enum _30 for value: 30
        /// </summary>
        [EnumMember(Value = "30")]
        _30 = 29,
        /// <summary>
        /// Enum _31 for value: 31
        /// </summary>
        [EnumMember(Value = "31")]
        _31 = 30    }
}
