/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DogBreeds
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DogBreeds
    {
        /// <summary>
        /// Enum Undetermined for value: Undetermined
        /// </summary>
        [EnumMember(Value = "Undetermined")]
        Undetermined = 0,
        /// <summary>
        /// Enum Akita for value: Akita
        /// </summary>
        [EnumMember(Value = "Akita")]
        Akita = 1,
        /// <summary>
        /// Enum AmericanBulldog for value: American Bulldog
        /// </summary>
        [EnumMember(Value = "American Bulldog")]
        AmericanBulldog = 2,
        /// <summary>
        /// Enum AmericanEskimoDog for value: American Eskimo Dog
        /// </summary>
        [EnumMember(Value = "American Eskimo Dog")]
        AmericanEskimoDog = 3,
        /// <summary>
        /// Enum AustralianCattleDog for value: Australian Cattle Dog
        /// </summary>
        [EnumMember(Value = "Australian Cattle Dog")]
        AustralianCattleDog = 4,
        /// <summary>
        /// Enum AustralianShepherd for value: Australian Shepherd
        /// </summary>
        [EnumMember(Value = "Australian Shepherd")]
        AustralianShepherd = 5,
        /// <summary>
        /// Enum Basenji for value: Basenji
        /// </summary>
        [EnumMember(Value = "Basenji")]
        Basenji = 6,
        /// <summary>
        /// Enum BassetHound for value: Basset Hound
        /// </summary>
        [EnumMember(Value = "Basset Hound")]
        BassetHound = 7,
        /// <summary>
        /// Enum Beagle for value: Beagle
        /// </summary>
        [EnumMember(Value = "Beagle")]
        Beagle = 8,
        /// <summary>
        /// Enum BerneseMountainDog for value: Bernese Mountain Dog
        /// </summary>
        [EnumMember(Value = "Bernese Mountain Dog")]
        BerneseMountainDog = 9,
        /// <summary>
        /// Enum BichonFrise for value: Bichon Frise
        /// </summary>
        [EnumMember(Value = "Bichon Frise")]
        BichonFrise = 10,
        /// <summary>
        /// Enum Bloodhound for value: Bloodhound
        /// </summary>
        [EnumMember(Value = "Bloodhound")]
        Bloodhound = 11,
        /// <summary>
        /// Enum BorderCollie for value: Border Collie
        /// </summary>
        [EnumMember(Value = "Border Collie")]
        BorderCollie = 12,
        /// <summary>
        /// Enum BostonTerrier for value: Boston Terrier
        /// </summary>
        [EnumMember(Value = "Boston Terrier")]
        BostonTerrier = 13,
        /// <summary>
        /// Enum BoxerScottish for value: Boxer Scottish
        /// </summary>
        [EnumMember(Value = "Boxer Scottish")]
        BoxerScottish = 14,
        /// <summary>
        /// Enum BrittanySpaniel for value: Brittany Spaniel
        /// </summary>
        [EnumMember(Value = "Brittany Spaniel")]
        BrittanySpaniel = 15,
        /// <summary>
        /// Enum BullTerrier for value: Bull Terrier
        /// </summary>
        [EnumMember(Value = "Bull Terrier")]
        BullTerrier = 16,
        /// <summary>
        /// Enum Bulldog for value: Bulldog
        /// </summary>
        [EnumMember(Value = "Bulldog")]
        Bulldog = 17,
        /// <summary>
        /// Enum Bullmastiff for value: Bullmastiff
        /// </summary>
        [EnumMember(Value = "Bullmastiff")]
        Bullmastiff = 18,
        /// <summary>
        /// Enum CatahoulaLeopardDog for value: Catahoula Leopard Dog
        /// </summary>
        [EnumMember(Value = "Catahoula Leopard Dog")]
        CatahoulaLeopardDog = 19,
        /// <summary>
        /// Enum CavalierKingCharlesSpaniel for value: Cavalier King Charles Spaniel
        /// </summary>
        [EnumMember(Value = "Cavalier King Charles Spaniel")]
        CavalierKingCharlesSpaniel = 20,
        /// <summary>
        /// Enum Chihuahua for value: Chihuahua
        /// </summary>
        [EnumMember(Value = "Chihuahua")]
        Chihuahua = 21,
        /// <summary>
        /// Enum ChineseCrested for value: Chinese Crested
        /// </summary>
        [EnumMember(Value = "Chinese Crested")]
        ChineseCrested = 22,
        /// <summary>
        /// Enum ChowChow for value: Chow Chow
        /// </summary>
        [EnumMember(Value = "Chow Chow")]
        ChowChow = 23,
        /// <summary>
        /// Enum Cockapoo for value: Cockapoo
        /// </summary>
        [EnumMember(Value = "Cockapoo")]
        Cockapoo = 24,
        /// <summary>
        /// Enum CockerSpaniel for value: Cocker Spaniel
        /// </summary>
        [EnumMember(Value = "Cocker Spaniel")]
        CockerSpaniel = 25,
        /// <summary>
        /// Enum Collie for value: Collie
        /// </summary>
        [EnumMember(Value = "Collie")]
        Collie = 26,
        /// <summary>
        /// Enum Dalmatian for value: Dalmatian
        /// </summary>
        [EnumMember(Value = "Dalmatian")]
        Dalmatian = 27,
        /// <summary>
        /// Enum Dashshund for value: Dashshund
        /// </summary>
        [EnumMember(Value = "Dashshund")]
        Dashshund = 28,
        /// <summary>
        /// Enum DobermanPinscher for value: Doberman Pinscher
        /// </summary>
        [EnumMember(Value = "Doberman Pinscher")]
        DobermanPinscher = 29,
        /// <summary>
        /// Enum EnglishSetter for value: English Setter
        /// </summary>
        [EnumMember(Value = "English Setter")]
        EnglishSetter = 30,
        /// <summary>
        /// Enum FlatCoatedRetriever for value: Flat-Coated Retriever
        /// </summary>
        [EnumMember(Value = "Flat-Coated Retriever")]
        FlatCoatedRetriever = 31,
        /// <summary>
        /// Enum FoxTerrier for value: Fox Terrier
        /// </summary>
        [EnumMember(Value = "Fox Terrier")]
        FoxTerrier = 32,
        /// <summary>
        /// Enum FrenchBulldog for value: French Bulldog
        /// </summary>
        [EnumMember(Value = "French Bulldog")]
        FrenchBulldog = 33,
        /// <summary>
        /// Enum GermanShepherd for value: German Shepherd
        /// </summary>
        [EnumMember(Value = "German Shepherd")]
        GermanShepherd = 34,
        /// <summary>
        /// Enum GermanShorthairedPointer for value: German Shorthaired Pointer
        /// </summary>
        [EnumMember(Value = "German Shorthaired Pointer")]
        GermanShorthairedPointer = 35,
        /// <summary>
        /// Enum GoldenRetriever for value: Golden Retriever
        /// </summary>
        [EnumMember(Value = "Golden Retriever")]
        GoldenRetriever = 36,
        /// <summary>
        /// Enum Goldendoodle for value: Goldendoodle
        /// </summary>
        [EnumMember(Value = "Goldendoodle")]
        Goldendoodle = 37,
        /// <summary>
        /// Enum GreatDane for value: Great Dane
        /// </summary>
        [EnumMember(Value = "Great Dane")]
        GreatDane = 38,
        /// <summary>
        /// Enum GreatPyrenees for value: Great Pyrenees
        /// </summary>
        [EnumMember(Value = "Great Pyrenees")]
        GreatPyrenees = 39,
        /// <summary>
        /// Enum Greyhound for value: Greyhound
        /// </summary>
        [EnumMember(Value = "Greyhound")]
        Greyhound = 40,
        /// <summary>
        /// Enum Havanese for value: Havanese
        /// </summary>
        [EnumMember(Value = "Havanese")]
        Havanese = 41,
        /// <summary>
        /// Enum IrishSetter for value: Irish Setter
        /// </summary>
        [EnumMember(Value = "Irish Setter")]
        IrishSetter = 42,
        /// <summary>
        /// Enum JackRussellTerrier for value: Jack Russell Terrier
        /// </summary>
        [EnumMember(Value = "Jack Russell Terrier")]
        JackRussellTerrier = 43,
        /// <summary>
        /// Enum Labradoodle for value: Labradoodle
        /// </summary>
        [EnumMember(Value = "Labradoodle")]
        Labradoodle = 44    }
}
