/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DogColors
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DogColors
    {
        /// <summary>
        /// Enum Black for value: Black
        /// </summary>
        [EnumMember(Value = "Black")]
        Black = 0,
        /// <summary>
        /// Enum BlackandWhite for value: Black and White
        /// </summary>
        [EnumMember(Value = "Black and White")]
        BlackandWhite = 1,
        /// <summary>
        /// Enum White for value: White
        /// </summary>
        [EnumMember(Value = "White")]
        White = 2,
        /// <summary>
        /// Enum Brindle for value: Brindle
        /// </summary>
        [EnumMember(Value = "Brindle")]
        Brindle = 3,
        /// <summary>
        /// Enum TriColor for value: Tri-Color
        /// </summary>
        [EnumMember(Value = "Tri-Color")]
        TriColor = 4,
        /// <summary>
        /// Enum Brown for value: Brown
        /// </summary>
        [EnumMember(Value = "Brown")]
        Brown = 5,
        /// <summary>
        /// Enum BrownandWhite for value: Brown and White
        /// </summary>
        [EnumMember(Value = "Brown and White")]
        BrownandWhite = 6,
        /// <summary>
        /// Enum GrayBlue for value: Gray/Blue
        /// </summary>
        [EnumMember(Value = "Gray/Blue")]
        GrayBlue = 7,
        /// <summary>
        /// Enum GrayandWhite for value: Gray and White
        /// </summary>
        [EnumMember(Value = "Gray and White")]
        GrayandWhite = 8,
        /// <summary>
        /// Enum RedCinnamon for value: Red/Cinnamon
        /// </summary>
        [EnumMember(Value = "Red/Cinnamon")]
        RedCinnamon = 9,
        /// <summary>
        /// Enum BlackandTan for value: Black and Tan
        /// </summary>
        [EnumMember(Value = "Black and Tan")]
        BlackandTan = 10,
        /// <summary>
        /// Enum Tan for value: Tan
        /// </summary>
        [EnumMember(Value = "Tan")]
        Tan = 11,
        /// <summary>
        /// Enum TanandWhite for value: Tan and White
        /// </summary>
        [EnumMember(Value = "Tan and White")]
        TanandWhite = 12    }
}
