/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines HalfHourMilitaryTimeSelect
    /// </summary>
        public enum HalfHourMilitaryTimeSelect
    {
        /// <summary>
        /// Enum _0000 for value: 00:00
        /// </summary>
        
        _0000 = 00:00,
        /// <summary>
        /// Enum _0030 for value: 00:30
        /// </summary>
        
        _0030 = 00:30,
        /// <summary>
        /// Enum _0100 for value: 01:00
        /// </summary>
        
        _0100 = 01:00,
        /// <summary>
        /// Enum _0130 for value: 01:30
        /// </summary>
        
        _0130 = 01:30,
        /// <summary>
        /// Enum _0200 for value: 02:00
        /// </summary>
        
        _0200 = 02:00,
        /// <summary>
        /// Enum _0230 for value: 02:30
        /// </summary>
        
        _0230 = 02:30,
        /// <summary>
        /// Enum _0300 for value: 03:00
        /// </summary>
        
        _0300 = 03:00,
        /// <summary>
        /// Enum _0330 for value: 03:30
        /// </summary>
        
        _0330 = 03:30,
        /// <summary>
        /// Enum _0400 for value: 04:00
        /// </summary>
        
        _0400 = 04:00,
        /// <summary>
        /// Enum _0430 for value: 04:30
        /// </summary>
        
        _0430 = 04:30,
        /// <summary>
        /// Enum _0500 for value: 05:00
        /// </summary>
        
        _0500 = 05:00,
        /// <summary>
        /// Enum _0530 for value: 05:30
        /// </summary>
        
        _0530 = 05:30,
        /// <summary>
        /// Enum _0600 for value: 06:00
        /// </summary>
        
        _0600 = 06:00,
        /// <summary>
        /// Enum _0630 for value: 06:30
        /// </summary>
        
        _0630 = 06:30,
        /// <summary>
        /// Enum _0700 for value: 07:00
        /// </summary>
        
        _0700 = 07:00,
        /// <summary>
        /// Enum _0730 for value: 07:30
        /// </summary>
        
        _0730 = 07:30,
        /// <summary>
        /// Enum _0800 for value: 08:00
        /// </summary>
        
        _0800 = 08:00,
        /// <summary>
        /// Enum _0830 for value: 08:30
        /// </summary>
        
        _0830 = 08:30,
        /// <summary>
        /// Enum _0900 for value: 09:00
        /// </summary>
        
        _0900 = 09:00,
        /// <summary>
        /// Enum _0930 for value: 09:30
        /// </summary>
        
        _0930 = 09:30,
        /// <summary>
        /// Enum _1000 for value: 10:00
        /// </summary>
        
        _1000 = 10:00,
        /// <summary>
        /// Enum _1030 for value: 10:30
        /// </summary>
        
        _1030 = 10:30,
        /// <summary>
        /// Enum _1100 for value: 11:00
        /// </summary>
        
        _1100 = 11:00,
        /// <summary>
        /// Enum _1130 for value: 11:30
        /// </summary>
        
        _1130 = 11:30,
        /// <summary>
        /// Enum _1200 for value: 12:00
        /// </summary>
        
        _1200 = 12:00,
        /// <summary>
        /// Enum _1230 for value: 12:30
        /// </summary>
        
        _1230 = 12:30,
        /// <summary>
        /// Enum _1300 for value: 13:00
        /// </summary>
        
        _1300 = 13:00,
        /// <summary>
        /// Enum _1330 for value: 13:30
        /// </summary>
        
        _1330 = 13:30,
        /// <summary>
        /// Enum _1400 for value: 14:00
        /// </summary>
        
        _1400 = 14:00,
        /// <summary>
        /// Enum _1430 for value: 14:30
        /// </summary>
        
        _1430 = 14:30,
        /// <summary>
        /// Enum _1500 for value: 15:00
        /// </summary>
        
        _1500 = 15:00,
        /// <summary>
        /// Enum _1530 for value: 15:30
        /// </summary>
        
        _1530 = 15:30,
        /// <summary>
        /// Enum _1600 for value: 16:00
        /// </summary>
        
        _1600 = 16:00,
        /// <summary>
        /// Enum _1630 for value: 16:30
        /// </summary>
        
        _1630 = 16:30,
        /// <summary>
        /// Enum _1700 for value: 17:00
        /// </summary>
        
        _1700 = 17:00,
        /// <summary>
        /// Enum _1730 for value: 17:30
        /// </summary>
        
        _1730 = 17:30,
        /// <summary>
        /// Enum _1800 for value: 18:00
        /// </summary>
        
        _1800 = 18:00,
        /// <summary>
        /// Enum _1830 for value: 18:30
        /// </summary>
        
        _1830 = 18:30,
        /// <summary>
        /// Enum _1900 for value: 19:00
        /// </summary>
        
        _1900 = 19:00,
        /// <summary>
        /// Enum _1930 for value: 19:30
        /// </summary>
        
        _1930 = 19:30,
        /// <summary>
        /// Enum _2000 for value: 20:00
        /// </summary>
        
        _2000 = 20:00,
        /// <summary>
        /// Enum _2030 for value: 20:30
        /// </summary>
        
        _2030 = 20:30,
        /// <summary>
        /// Enum _2100 for value: 21:00
        /// </summary>
        
        _2100 = 21:00,
        /// <summary>
        /// Enum _2130 for value: 21:30
        /// </summary>
        
        _2130 = 21:30,
        /// <summary>
        /// Enum _2200 for value: 22:00
        /// </summary>
        
        _2200 = 22:00,
        /// <summary>
        /// Enum _2230 for value: 22:30
        /// </summary>
        
        _2230 = 22:30,
        /// <summary>
        /// Enum _2300 for value: 23:00
        /// </summary>
        
        _2300 = 23:00,
        /// <summary>
        /// Enum _2330 for value: 23:30
        /// </summary>
        
        _2330 = 23:30    }
}
