/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines MonthSelect
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum MonthSelect
    {
        /// <summary>
        /// Enum January for value: January
        /// </summary>
        [EnumMember(Value = "January")]
        January = 0,
        /// <summary>
        /// Enum February for value: February
        /// </summary>
        [EnumMember(Value = "February")]
        February = 1,
        /// <summary>
        /// Enum March for value: March
        /// </summary>
        [EnumMember(Value = "March")]
        March = 2,
        /// <summary>
        /// Enum April for value: April
        /// </summary>
        [EnumMember(Value = "April")]
        April = 3,
        /// <summary>
        /// Enum May for value: May
        /// </summary>
        [EnumMember(Value = "May")]
        May = 4,
        /// <summary>
        /// Enum June for value: June
        /// </summary>
        [EnumMember(Value = "June")]
        June = 5,
        /// <summary>
        /// Enum July for value: July
        /// </summary>
        [EnumMember(Value = "July")]
        July = 6,
        /// <summary>
        /// Enum August for value: August
        /// </summary>
        [EnumMember(Value = "August")]
        August = 7,
        /// <summary>
        /// Enum September for value: September
        /// </summary>
        [EnumMember(Value = "September")]
        September = 8,
        /// <summary>
        /// Enum October for value: October
        /// </summary>
        [EnumMember(Value = "October")]
        October = 9,
        /// <summary>
        /// Enum November for value: November
        /// </summary>
        [EnumMember(Value = "November")]
        November = 10,
        /// <summary>
        /// Enum December for value: December
        /// </summary>
        [EnumMember(Value = "December")]
        December = 11    }
}
