/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Species
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Species
    {
        /// <summary>
        /// Enum Dog for value: Dog
        /// </summary>
        [EnumMember(Value = "Dog")]
        Dog = 0,
        /// <summary>
        /// Enum Cat for value: Cat
        /// </summary>
        [EnumMember(Value = "Cat")]
        Cat = 1    }
}
