/* 
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines YearSelect
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum YearSelect
    {
        /// <summary>
        /// Enum _2000 for value: 2000
        /// </summary>
        [EnumMember(Value = "2000")]
        _2000 = 0,
        /// <summary>
        /// Enum _2001 for value: 2001
        /// </summary>
        [EnumMember(Value = "2001")]
        _2001 = 1,
        /// <summary>
        /// Enum _2002 for value: 2002
        /// </summary>
        [EnumMember(Value = "2002")]
        _2002 = 2,
        /// <summary>
        /// Enum _2003 for value: 2003
        /// </summary>
        [EnumMember(Value = "2003")]
        _2003 = 3,
        /// <summary>
        /// Enum _2004 for value: 2004
        /// </summary>
        [EnumMember(Value = "2004")]
        _2004 = 4,
        /// <summary>
        /// Enum _2005 for value: 2005
        /// </summary>
        [EnumMember(Value = "2005")]
        _2005 = 5,
        /// <summary>
        /// Enum _2006 for value: 2006
        /// </summary>
        [EnumMember(Value = "2006")]
        _2006 = 6,
        /// <summary>
        /// Enum _2007 for value: 2007
        /// </summary>
        [EnumMember(Value = "2007")]
        _2007 = 7,
        /// <summary>
        /// Enum _2008 for value: 2008
        /// </summary>
        [EnumMember(Value = "2008")]
        _2008 = 8,
        /// <summary>
        /// Enum _2009 for value: 2009
        /// </summary>
        [EnumMember(Value = "2009")]
        _2009 = 9,
        /// <summary>
        /// Enum _2010 for value: 2010
        /// </summary>
        [EnumMember(Value = "2010")]
        _2010 = 10,
        /// <summary>
        /// Enum _2011 for value: 2011
        /// </summary>
        [EnumMember(Value = "2011")]
        _2011 = 11,
        /// <summary>
        /// Enum _2012 for value: 2012
        /// </summary>
        [EnumMember(Value = "2012")]
        _2012 = 12,
        /// <summary>
        /// Enum _2013 for value: 2013
        /// </summary>
        [EnumMember(Value = "2013")]
        _2013 = 13,
        /// <summary>
        /// Enum _2014 for value: 2014
        /// </summary>
        [EnumMember(Value = "2014")]
        _2014 = 14,
        /// <summary>
        /// Enum _2015 for value: 2015
        /// </summary>
        [EnumMember(Value = "2015")]
        _2015 = 15,
        /// <summary>
        /// Enum _2016 for value: 2016
        /// </summary>
        [EnumMember(Value = "2016")]
        _2016 = 16,
        /// <summary>
        /// Enum _2017 for value: 2017
        /// </summary>
        [EnumMember(Value = "2017")]
        _2017 = 17,
        /// <summary>
        /// Enum _2018 for value: 2018
        /// </summary>
        [EnumMember(Value = "2018")]
        _2018 = 18,
        /// <summary>
        /// Enum _2019 for value: 2019
        /// </summary>
        [EnumMember(Value = "2019")]
        _2019 = 19,
        /// <summary>
        /// Enum _2020 for value: 2020
        /// </summary>
        [EnumMember(Value = "2020")]
        _2020 = 20,
        /// <summary>
        /// Enum _2021 for value: 2021
        /// </summary>
        [EnumMember(Value = "2021")]
        _2021 = 21,
        /// <summary>
        /// Enum _2022 for value: 2022
        /// </summary>
        [EnumMember(Value = "2022")]
        _2022 = 22,
        /// <summary>
        /// Enum _2023 for value: 2023
        /// </summary>
        [EnumMember(Value = "2023")]
        _2023 = 23,
        /// <summary>
        /// Enum _2024 for value: 2024
        /// </summary>
        [EnumMember(Value = "2024")]
        _2024 = 24,
        /// <summary>
        /// Enum _2025 for value: 2025
        /// </summary>
        [EnumMember(Value = "2025")]
        _2025 = 25,
        /// <summary>
        /// Enum _2026 for value: 2026
        /// </summary>
        [EnumMember(Value = "2026")]
        _2026 = 26,
        /// <summary>
        /// Enum _2027 for value: 2027
        /// </summary>
        [EnumMember(Value = "2027")]
        _2027 = 27,
        /// <summary>
        /// Enum _2028 for value: 2028
        /// </summary>
        [EnumMember(Value = "2028")]
        _2028 = 28,
        /// <summary>
        /// Enum _2029 for value: 2029
        /// </summary>
        [EnumMember(Value = "2029")]
        _2029 = 29,
        /// <summary>
        /// Enum _2030 for value: 2030
        /// </summary>
        [EnumMember(Value = "2030")]
        _2030 = 30,
        /// <summary>
        /// Enum _2031 for value: 2031
        /// </summary>
        [EnumMember(Value = "2031")]
        _2031 = 31,
        /// <summary>
        /// Enum _2032 for value: 2032
        /// </summary>
        [EnumMember(Value = "2032")]
        _2032 = 32,
        /// <summary>
        /// Enum _2033 for value: 2033
        /// </summary>
        [EnumMember(Value = "2033")]
        _2033 = 33,
        /// <summary>
        /// Enum _2034 for value: 2034
        /// </summary>
        [EnumMember(Value = "2034")]
        _2034 = 34,
        /// <summary>
        /// Enum _2035 for value: 2035
        /// </summary>
        [EnumMember(Value = "2035")]
        _2035 = 35,
        /// <summary>
        /// Enum _2036 for value: 2036
        /// </summary>
        [EnumMember(Value = "2036")]
        _2036 = 36,
        /// <summary>
        /// Enum _2037 for value: 2037
        /// </summary>
        [EnumMember(Value = "2037")]
        _2037 = 37,
        /// <summary>
        /// Enum _2038 for value: 2038
        /// </summary>
        [EnumMember(Value = "2038")]
        _2038 = 38,
        /// <summary>
        /// Enum _2039 for value: 2039
        /// </summary>
        [EnumMember(Value = "2039")]
        _2039 = 39,
        /// <summary>
        /// Enum _2040 for value: 2040
        /// </summary>
        [EnumMember(Value = "2040")]
        _2040 = 40,
        /// <summary>
        /// Enum _2041 for value: 2041
        /// </summary>
        [EnumMember(Value = "2041")]
        _2041 = 41,
        /// <summary>
        /// Enum _2042 for value: 2042
        /// </summary>
        [EnumMember(Value = "2042")]
        _2042 = 42,
        /// <summary>
        /// Enum _2043 for value: 2043
        /// </summary>
        [EnumMember(Value = "2043")]
        _2043 = 43,
        /// <summary>
        /// Enum _2044 for value: 2044
        /// </summary>
        [EnumMember(Value = "2044")]
        _2044 = 44,
        /// <summary>
        /// Enum _2045 for value: 2045
        /// </summary>
        [EnumMember(Value = "2045")]
        _2045 = 45,
        /// <summary>
        /// Enum _2046 for value: 2046
        /// </summary>
        [EnumMember(Value = "2046")]
        _2046 = 46,
        /// <summary>
        /// Enum _2047 for value: 2047
        /// </summary>
        [EnumMember(Value = "2047")]
        _2047 = 47,
        /// <summary>
        /// Enum _2048 for value: 2048
        /// </summary>
        [EnumMember(Value = "2048")]
        _2048 = 48,
        /// <summary>
        /// Enum _2049 for value: 2049
        /// </summary>
        [EnumMember(Value = "2049")]
        _2049 = 49    }
}
