// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Animal Rescue")]
[assembly: AssemblyDescriptionAttribute("Software to save critters")]
[assembly: AssemblyCompanyAttribute("Animal Rescue Foundation")]
[assembly: AssemblyProductAttribute("ACnimalRescue")]
[assembly: AssemblyCopyrightAttribute("Copyright © Animal Rescue Foundation 2015")]
[assembly: AssemblyTrademarkAttribute("Animal Rescue Foundation")]
[assembly: GuidAttribute("822D4F9F-A3AE-4257-B986-534189E6FEE7")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
