/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets CatBreeds
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CatBreeds
        {
            /// <summary>
            /// Enum UndeterminedEnum for Undetermined
            /// </summary>
            [EnumMember(Value = "Undetermined")]
            UndeterminedEnum = 0,
            /// <summary>
            /// Enum AbyssinianEnum for Abyssinian
            /// </summary>
            [EnumMember(Value = "Abyssinian")]
            AbyssinianEnum = 1,
            /// <summary>
            /// Enum AmericanCurlEnum for American Curl
            /// </summary>
            [EnumMember(Value = "American Curl")]
            AmericanCurlEnum = 2,
            /// <summary>
            /// Enum BengalEnum for Bengal
            /// </summary>
            [EnumMember(Value = "Bengal")]
            BengalEnum = 3,
            /// <summary>
            /// Enum DomesticLonghairEnum for Domestic Longhair
            /// </summary>
            [EnumMember(Value = "Domestic Longhair")]
            DomesticLonghairEnum = 4,
            /// <summary>
            /// Enum DomesticMediumhairEnum for Domestic Mediumhair
            /// </summary>
            [EnumMember(Value = "Domestic Mediumhair")]
            DomesticMediumhairEnum = 5,
            /// <summary>
            /// Enum DomesticShorthairEnum for Domestic Shorthair
            /// </summary>
            [EnumMember(Value = "Domestic Shorthair")]
            DomesticShorthairEnum = 6,
            /// <summary>
            /// Enum HimalayanEnum for Himalayan
            /// </summary>
            [EnumMember(Value = "Himalayan")]
            HimalayanEnum = 7,
            /// <summary>
            /// Enum MaineCoonEnum for Maine Coon
            /// </summary>
            [EnumMember(Value = "Maine Coon")]
            MaineCoonEnum = 8,
            /// <summary>
            /// Enum ManxEnum for Manx
            /// </summary>
            [EnumMember(Value = "Manx")]
            ManxEnum = 9,
            /// <summary>
            /// Enum PersianEnum for Persian
            /// </summary>
            [EnumMember(Value = "Persian")]
            PersianEnum = 10,
            /// <summary>
            /// Enum RagaMuffinEnum for RagaMuffin
            /// </summary>
            [EnumMember(Value = "RagaMuffin")]
            RagaMuffinEnum = 11,
            /// <summary>
            /// Enum RagdollEnum for Ragdoll
            /// </summary>
            [EnumMember(Value = "Ragdoll")]
            RagdollEnum = 12,
            /// <summary>
            /// Enum RussianBlueEnum for Russian Blue
            /// </summary>
            [EnumMember(Value = "Russian Blue")]
            RussianBlueEnum = 13,
            /// <summary>
            /// Enum FoldEnum for Fold
            /// </summary>
            [EnumMember(Value = "Fold")]
            FoldEnum = 14,
            /// <summary>
            /// Enum SiameseEnum for Siamese
            /// </summary>
            [EnumMember(Value = "Siamese")]
            SiameseEnum = 15,
            /// <summary>
            /// Enum SnowshoeEnum for Snowshoe
            /// </summary>
            [EnumMember(Value = "Snowshoe")]
            SnowshoeEnum = 16,
            /// <summary>
            /// Enum SphynxEnum for Sphynx
            /// </summary>
            [EnumMember(Value = "Sphynx")]
            SphynxEnum = 17        }
}
