/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets CatColors
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CatColors
        {
            /// <summary>
            /// Enum WhiteEnum for White
            /// </summary>
            [EnumMember(Value = "White")]
            WhiteEnum = 0,
            /// <summary>
            /// Enum BlackEnum for Black
            /// </summary>
            [EnumMember(Value = "Black")]
            BlackEnum = 1,
            /// <summary>
            /// Enum BlackAndWhiteEnum for Black and White
            /// </summary>
            [EnumMember(Value = "Black and White")]
            BlackAndWhiteEnum = 2,
            /// <summary>
            /// Enum OrangeTabbyEnum for Orange Tabby
            /// </summary>
            [EnumMember(Value = "Orange Tabby")]
            OrangeTabbyEnum = 3,
            /// <summary>
            /// Enum OrangeAndWhiteEnum for Orange and White
            /// </summary>
            [EnumMember(Value = "Orange and White")]
            OrangeAndWhiteEnum = 4,
            /// <summary>
            /// Enum BrownEnum for Brown
            /// </summary>
            [EnumMember(Value = "Brown")]
            BrownEnum = 5,
            /// <summary>
            /// Enum BrownTabbyEnum for Brown Tabby
            /// </summary>
            [EnumMember(Value = "Brown Tabby")]
            BrownTabbyEnum = 6,
            /// <summary>
            /// Enum BrownAndWhiteEnum for Brown and White
            /// </summary>
            [EnumMember(Value = "Brown and White")]
            BrownAndWhiteEnum = 7,
            /// <summary>
            /// Enum GrayEnum for Gray
            /// </summary>
            [EnumMember(Value = "Gray")]
            GrayEnum = 8,
            /// <summary>
            /// Enum GrayAndWhiteEnum for Gray and White
            /// </summary>
            [EnumMember(Value = "Gray and White")]
            GrayAndWhiteEnum = 9,
            /// <summary>
            /// Enum GrayTabbyEnum for Gray Tabby
            /// </summary>
            [EnumMember(Value = "Gray Tabby")]
            GrayTabbyEnum = 10,
            /// <summary>
            /// Enum SilverEnum for Silver
            /// </summary>
            [EnumMember(Value = "Silver")]
            SilverEnum = 11,
            /// <summary>
            /// Enum SilverAndWhiteEnum for Silver and White
            /// </summary>
            [EnumMember(Value = "Silver and White")]
            SilverAndWhiteEnum = 12,
            /// <summary>
            /// Enum SilverTabbyEnum for Silver Tabby
            /// </summary>
            [EnumMember(Value = "Silver Tabby")]
            SilverTabbyEnum = 13,
            /// <summary>
            /// Enum BuffEnum for Buff
            /// </summary>
            [EnumMember(Value = "Buff")]
            BuffEnum = 14,
            /// <summary>
            /// Enum BuffAndWhiteEnum for Buff and White
            /// </summary>
            [EnumMember(Value = "Buff and White")]
            BuffAndWhiteEnum = 15,
            /// <summary>
            /// Enum BuffTabbyEnum for Buff Tabby
            /// </summary>
            [EnumMember(Value = "Buff Tabby")]
            BuffTabbyEnum = 16,
            /// <summary>
            /// Enum SealPointEnum for Seal Point
            /// </summary>
            [EnumMember(Value = "Seal Point")]
            SealPointEnum = 17,
            /// <summary>
            /// Enum FlamePointEnum for Flame Point
            /// </summary>
            [EnumMember(Value = "Flame Point")]
            FlamePointEnum = 18,
            /// <summary>
            /// Enum LavendarLilacPointEnum for Lavendar/Lilac Point
            /// </summary>
            [EnumMember(Value = "Lavendar/Lilac Point")]
            LavendarLilacPointEnum = 19,
            /// <summary>
            /// Enum SnowshoeEnum for Snowshoe
            /// </summary>
            [EnumMember(Value = "Snowshoe")]
            SnowshoeEnum = 20,
            /// <summary>
            /// Enum CalicoEnum for Calico
            /// </summary>
            [EnumMember(Value = "Calico")]
            CalicoEnum = 21,
            /// <summary>
            /// Enum TortieEnum for Tortie
            /// </summary>
            [EnumMember(Value = "Tortie")]
            TortieEnum = 22,
            /// <summary>
            /// Enum DiluteCalicoEnum for Dilute Calico
            /// </summary>
            [EnumMember(Value = "Dilute Calico")]
            DiluteCalicoEnum = 23        }
}
