/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets DayOfMonthSelect
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DayOfMonthSelect
        {
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            [EnumMember(Value = "1")]
            _1Enum = 0,
            /// <summary>
            /// Enum _2Enum for 2
            /// </summary>
            [EnumMember(Value = "2")]
            _2Enum = 1,
            /// <summary>
            /// Enum _3Enum for 3
            /// </summary>
            [EnumMember(Value = "3")]
            _3Enum = 2,
            /// <summary>
            /// Enum _4Enum for 4
            /// </summary>
            [EnumMember(Value = "4")]
            _4Enum = 3,
            /// <summary>
            /// Enum _5Enum for 5
            /// </summary>
            [EnumMember(Value = "5")]
            _5Enum = 4,
            /// <summary>
            /// Enum _6Enum for 6
            /// </summary>
            [EnumMember(Value = "6")]
            _6Enum = 5,
            /// <summary>
            /// Enum _7Enum for 7
            /// </summary>
            [EnumMember(Value = "7")]
            _7Enum = 6,
            /// <summary>
            /// Enum _8Enum for 8
            /// </summary>
            [EnumMember(Value = "8")]
            _8Enum = 7,
            /// <summary>
            /// Enum _9Enum for 9
            /// </summary>
            [EnumMember(Value = "9")]
            _9Enum = 8,
            /// <summary>
            /// Enum _10Enum for 10
            /// </summary>
            [EnumMember(Value = "10")]
            _10Enum = 9,
            /// <summary>
            /// Enum _11Enum for 11
            /// </summary>
            [EnumMember(Value = "11")]
            _11Enum = 10,
            /// <summary>
            /// Enum _12Enum for 12
            /// </summary>
            [EnumMember(Value = "12")]
            _12Enum = 11,
            /// <summary>
            /// Enum _13Enum for 13
            /// </summary>
            [EnumMember(Value = "13")]
            _13Enum = 12,
            /// <summary>
            /// Enum _14Enum for 14
            /// </summary>
            [EnumMember(Value = "14")]
            _14Enum = 13,
            /// <summary>
            /// Enum _15Enum for 15
            /// </summary>
            [EnumMember(Value = "15")]
            _15Enum = 14,
            /// <summary>
            /// Enum _16Enum for 16
            /// </summary>
            [EnumMember(Value = "16")]
            _16Enum = 15,
            /// <summary>
            /// Enum _17Enum for 17
            /// </summary>
            [EnumMember(Value = "17")]
            _17Enum = 16,
            /// <summary>
            /// Enum _18Enum for 18
            /// </summary>
            [EnumMember(Value = "18")]
            _18Enum = 17,
            /// <summary>
            /// Enum _19Enum for 19
            /// </summary>
            [EnumMember(Value = "19")]
            _19Enum = 18,
            /// <summary>
            /// Enum _20Enum for 20
            /// </summary>
            [EnumMember(Value = "20")]
            _20Enum = 19,
            /// <summary>
            /// Enum _21Enum for 21
            /// </summary>
            [EnumMember(Value = "21")]
            _21Enum = 20,
            /// <summary>
            /// Enum _22Enum for 22
            /// </summary>
            [EnumMember(Value = "22")]
            _22Enum = 21,
            /// <summary>
            /// Enum _23Enum for 23
            /// </summary>
            [EnumMember(Value = "23")]
            _23Enum = 22,
            /// <summary>
            /// Enum _24Enum for 24
            /// </summary>
            [EnumMember(Value = "24")]
            _24Enum = 23,
            /// <summary>
            /// Enum _25Enum for 25
            /// </summary>
            [EnumMember(Value = "25")]
            _25Enum = 24,
            /// <summary>
            /// Enum _26Enum for 26
            /// </summary>
            [EnumMember(Value = "26")]
            _26Enum = 25,
            /// <summary>
            /// Enum _27Enum for 27
            /// </summary>
            [EnumMember(Value = "27")]
            _27Enum = 26,
            /// <summary>
            /// Enum _28Enum for 28
            /// </summary>
            [EnumMember(Value = "28")]
            _28Enum = 27,
            /// <summary>
            /// Enum _29Enum for 29
            /// </summary>
            [EnumMember(Value = "29")]
            _29Enum = 28,
            /// <summary>
            /// Enum _30Enum for 30
            /// </summary>
            [EnumMember(Value = "30")]
            _30Enum = 29,
            /// <summary>
            /// Enum _31Enum for 31
            /// </summary>
            [EnumMember(Value = "31")]
            _31Enum = 30        }
}
