/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets DogBreeds
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DogBreeds
        {
            /// <summary>
            /// Enum UndeterminedEnum for Undetermined
            /// </summary>
            [EnumMember(Value = "Undetermined")]
            UndeterminedEnum = 0,
            /// <summary>
            /// Enum AkitaEnum for Akita
            /// </summary>
            [EnumMember(Value = "Akita")]
            AkitaEnum = 1,
            /// <summary>
            /// Enum AmericanBulldogEnum for American Bulldog
            /// </summary>
            [EnumMember(Value = "American Bulldog")]
            AmericanBulldogEnum = 2,
            /// <summary>
            /// Enum AmericanEskimoDogEnum for American Eskimo Dog
            /// </summary>
            [EnumMember(Value = "American Eskimo Dog")]
            AmericanEskimoDogEnum = 3,
            /// <summary>
            /// Enum AustralianCattleDogEnum for Australian Cattle Dog
            /// </summary>
            [EnumMember(Value = "Australian Cattle Dog")]
            AustralianCattleDogEnum = 4,
            /// <summary>
            /// Enum AustralianShepherdEnum for Australian Shepherd
            /// </summary>
            [EnumMember(Value = "Australian Shepherd")]
            AustralianShepherdEnum = 5,
            /// <summary>
            /// Enum BasenjiEnum for Basenji
            /// </summary>
            [EnumMember(Value = "Basenji")]
            BasenjiEnum = 6,
            /// <summary>
            /// Enum BassetHoundEnum for Basset Hound
            /// </summary>
            [EnumMember(Value = "Basset Hound")]
            BassetHoundEnum = 7,
            /// <summary>
            /// Enum BeagleEnum for Beagle
            /// </summary>
            [EnumMember(Value = "Beagle")]
            BeagleEnum = 8,
            /// <summary>
            /// Enum BerneseMountainDogEnum for Bernese Mountain Dog
            /// </summary>
            [EnumMember(Value = "Bernese Mountain Dog")]
            BerneseMountainDogEnum = 9,
            /// <summary>
            /// Enum BichonFriseEnum for Bichon Frise
            /// </summary>
            [EnumMember(Value = "Bichon Frise")]
            BichonFriseEnum = 10,
            /// <summary>
            /// Enum BloodhoundEnum for Bloodhound
            /// </summary>
            [EnumMember(Value = "Bloodhound")]
            BloodhoundEnum = 11,
            /// <summary>
            /// Enum BorderCollieEnum for Border Collie
            /// </summary>
            [EnumMember(Value = "Border Collie")]
            BorderCollieEnum = 12,
            /// <summary>
            /// Enum BostonTerrierEnum for Boston Terrier
            /// </summary>
            [EnumMember(Value = "Boston Terrier")]
            BostonTerrierEnum = 13,
            /// <summary>
            /// Enum BoxerScottishEnum for Boxer Scottish
            /// </summary>
            [EnumMember(Value = "Boxer Scottish")]
            BoxerScottishEnum = 14,
            /// <summary>
            /// Enum BrittanySpanielEnum for Brittany Spaniel
            /// </summary>
            [EnumMember(Value = "Brittany Spaniel")]
            BrittanySpanielEnum = 15,
            /// <summary>
            /// Enum BullTerrierEnum for Bull Terrier
            /// </summary>
            [EnumMember(Value = "Bull Terrier")]
            BullTerrierEnum = 16,
            /// <summary>
            /// Enum BulldogEnum for Bulldog
            /// </summary>
            [EnumMember(Value = "Bulldog")]
            BulldogEnum = 17,
            /// <summary>
            /// Enum BullmastiffEnum for Bullmastiff
            /// </summary>
            [EnumMember(Value = "Bullmastiff")]
            BullmastiffEnum = 18,
            /// <summary>
            /// Enum CatahoulaLeopardDogEnum for Catahoula Leopard Dog
            /// </summary>
            [EnumMember(Value = "Catahoula Leopard Dog")]
            CatahoulaLeopardDogEnum = 19,
            /// <summary>
            /// Enum CavalierKingCharlesSpanielEnum for Cavalier King Charles Spaniel
            /// </summary>
            [EnumMember(Value = "Cavalier King Charles Spaniel")]
            CavalierKingCharlesSpanielEnum = 20,
            /// <summary>
            /// Enum ChihuahuaEnum for Chihuahua
            /// </summary>
            [EnumMember(Value = "Chihuahua")]
            ChihuahuaEnum = 21,
            /// <summary>
            /// Enum ChineseCrestedEnum for Chinese Crested
            /// </summary>
            [EnumMember(Value = "Chinese Crested")]
            ChineseCrestedEnum = 22,
            /// <summary>
            /// Enum ChowChowEnum for Chow Chow
            /// </summary>
            [EnumMember(Value = "Chow Chow")]
            ChowChowEnum = 23,
            /// <summary>
            /// Enum CockapooEnum for Cockapoo
            /// </summary>
            [EnumMember(Value = "Cockapoo")]
            CockapooEnum = 24,
            /// <summary>
            /// Enum CockerSpanielEnum for Cocker Spaniel
            /// </summary>
            [EnumMember(Value = "Cocker Spaniel")]
            CockerSpanielEnum = 25,
            /// <summary>
            /// Enum CollieEnum for Collie
            /// </summary>
            [EnumMember(Value = "Collie")]
            CollieEnum = 26,
            /// <summary>
            /// Enum DalmatianEnum for Dalmatian
            /// </summary>
            [EnumMember(Value = "Dalmatian")]
            DalmatianEnum = 27,
            /// <summary>
            /// Enum DashshundEnum for Dashshund
            /// </summary>
            [EnumMember(Value = "Dashshund")]
            DashshundEnum = 28,
            /// <summary>
            /// Enum DobermanPinscherEnum for Doberman Pinscher
            /// </summary>
            [EnumMember(Value = "Doberman Pinscher")]
            DobermanPinscherEnum = 29,
            /// <summary>
            /// Enum EnglishSetterEnum for English Setter
            /// </summary>
            [EnumMember(Value = "English Setter")]
            EnglishSetterEnum = 30,
            /// <summary>
            /// Enum FlatCoatedRetrieverEnum for Flat-Coated Retriever
            /// </summary>
            [EnumMember(Value = "Flat-Coated Retriever")]
            FlatCoatedRetrieverEnum = 31,
            /// <summary>
            /// Enum FoxTerrierEnum for Fox Terrier
            /// </summary>
            [EnumMember(Value = "Fox Terrier")]
            FoxTerrierEnum = 32,
            /// <summary>
            /// Enum FrenchBulldogEnum for French Bulldog
            /// </summary>
            [EnumMember(Value = "French Bulldog")]
            FrenchBulldogEnum = 33,
            /// <summary>
            /// Enum GermanShepherdEnum for German Shepherd
            /// </summary>
            [EnumMember(Value = "German Shepherd")]
            GermanShepherdEnum = 34,
            /// <summary>
            /// Enum GermanShorthairedPointerEnum for German Shorthaired Pointer
            /// </summary>
            [EnumMember(Value = "German Shorthaired Pointer")]
            GermanShorthairedPointerEnum = 35,
            /// <summary>
            /// Enum GoldenRetrieverEnum for Golden Retriever
            /// </summary>
            [EnumMember(Value = "Golden Retriever")]
            GoldenRetrieverEnum = 36,
            /// <summary>
            /// Enum GoldendoodleEnum for Goldendoodle
            /// </summary>
            [EnumMember(Value = "Goldendoodle")]
            GoldendoodleEnum = 37,
            /// <summary>
            /// Enum GreatDaneEnum for Great Dane
            /// </summary>
            [EnumMember(Value = "Great Dane")]
            GreatDaneEnum = 38,
            /// <summary>
            /// Enum GreatPyreneesEnum for Great Pyrenees
            /// </summary>
            [EnumMember(Value = "Great Pyrenees")]
            GreatPyreneesEnum = 39,
            /// <summary>
            /// Enum GreyhoundEnum for Greyhound
            /// </summary>
            [EnumMember(Value = "Greyhound")]
            GreyhoundEnum = 40,
            /// <summary>
            /// Enum HavaneseEnum for Havanese
            /// </summary>
            [EnumMember(Value = "Havanese")]
            HavaneseEnum = 41,
            /// <summary>
            /// Enum IrishSetterEnum for Irish Setter
            /// </summary>
            [EnumMember(Value = "Irish Setter")]
            IrishSetterEnum = 42,
            /// <summary>
            /// Enum JackRussellTerrierEnum for Jack Russell Terrier
            /// </summary>
            [EnumMember(Value = "Jack Russell Terrier")]
            JackRussellTerrierEnum = 43,
            /// <summary>
            /// Enum LabradoodleEnum for Labradoodle
            /// </summary>
            [EnumMember(Value = "Labradoodle")]
            LabradoodleEnum = 44        }
}
