/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets DogColors
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DogColors
        {
            /// <summary>
            /// Enum BlackEnum for Black
            /// </summary>
            [EnumMember(Value = "Black")]
            BlackEnum = 0,
            /// <summary>
            /// Enum BlackAndWhiteEnum for Black and White
            /// </summary>
            [EnumMember(Value = "Black and White")]
            BlackAndWhiteEnum = 1,
            /// <summary>
            /// Enum WhiteEnum for White
            /// </summary>
            [EnumMember(Value = "White")]
            WhiteEnum = 2,
            /// <summary>
            /// Enum BrindleEnum for Brindle
            /// </summary>
            [EnumMember(Value = "Brindle")]
            BrindleEnum = 3,
            /// <summary>
            /// Enum TriColorEnum for Tri-Color
            /// </summary>
            [EnumMember(Value = "Tri-Color")]
            TriColorEnum = 4,
            /// <summary>
            /// Enum BrownEnum for Brown
            /// </summary>
            [EnumMember(Value = "Brown")]
            BrownEnum = 5,
            /// <summary>
            /// Enum BrownAndWhiteEnum for Brown and White
            /// </summary>
            [EnumMember(Value = "Brown and White")]
            BrownAndWhiteEnum = 6,
            /// <summary>
            /// Enum GrayBlueEnum for Gray/Blue
            /// </summary>
            [EnumMember(Value = "Gray/Blue")]
            GrayBlueEnum = 7,
            /// <summary>
            /// Enum GrayAndWhiteEnum for Gray and White
            /// </summary>
            [EnumMember(Value = "Gray and White")]
            GrayAndWhiteEnum = 8,
            /// <summary>
            /// Enum RedCinnamonEnum for Red/Cinnamon
            /// </summary>
            [EnumMember(Value = "Red/Cinnamon")]
            RedCinnamonEnum = 9,
            /// <summary>
            /// Enum BlackAndTanEnum for Black and Tan
            /// </summary>
            [EnumMember(Value = "Black and Tan")]
            BlackAndTanEnum = 10,
            /// <summary>
            /// Enum TanEnum for Tan
            /// </summary>
            [EnumMember(Value = "Tan")]
            TanEnum = 11,
            /// <summary>
            /// Enum TanAndWhiteEnum for Tan and White
            /// </summary>
            [EnumMember(Value = "Tan and White")]
            TanAndWhiteEnum = 12        }
}
