/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets MonthSelect
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MonthSelect
        {
            /// <summary>
            /// Enum JanuaryEnum for January
            /// </summary>
            [EnumMember(Value = "January")]
            JanuaryEnum = 0,
            /// <summary>
            /// Enum FebruaryEnum for February
            /// </summary>
            [EnumMember(Value = "February")]
            FebruaryEnum = 1,
            /// <summary>
            /// Enum MarchEnum for March
            /// </summary>
            [EnumMember(Value = "March")]
            MarchEnum = 2,
            /// <summary>
            /// Enum AprilEnum for April
            /// </summary>
            [EnumMember(Value = "April")]
            AprilEnum = 3,
            /// <summary>
            /// Enum MayEnum for May
            /// </summary>
            [EnumMember(Value = "May")]
            MayEnum = 4,
            /// <summary>
            /// Enum JuneEnum for June
            /// </summary>
            [EnumMember(Value = "June")]
            JuneEnum = 5,
            /// <summary>
            /// Enum JulyEnum for July
            /// </summary>
            [EnumMember(Value = "July")]
            JulyEnum = 6,
            /// <summary>
            /// Enum AugustEnum for August
            /// </summary>
            [EnumMember(Value = "August")]
            AugustEnum = 7,
            /// <summary>
            /// Enum SeptemberEnum for September
            /// </summary>
            [EnumMember(Value = "September")]
            SeptemberEnum = 8,
            /// <summary>
            /// Enum OctoberEnum for October
            /// </summary>
            [EnumMember(Value = "October")]
            OctoberEnum = 9,
            /// <summary>
            /// Enum NovemberEnum for November
            /// </summary>
            [EnumMember(Value = "November")]
            NovemberEnum = 10,
            /// <summary>
            /// Enum DecemberEnum for December
            /// </summary>
            [EnumMember(Value = "December")]
            DecemberEnum = 11        }
}
