/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets AdoptionStatus
        /// </summary>
        
        public enum AdoptionStatus
        {
            /// <summary>
            /// Enum AdoptionPendingEnum for Adoption Pending
            /// </summary>
            
            AdoptionPendingEnum = Adoption Pending,
            /// <summary>
            /// Enum AvailableEnum for Available
            /// </summary>
            
            AvailableEnum = Available,
            /// <summary>
            /// Enum AvailablePendingSpayNeuterEnum for Available Pending Spay/Neuter
            /// </summary>
            
            AvailablePendingSpayNeuterEnum = Available Pending Spay/Neuter,
            /// <summary>
            /// Enum MedicalHoldEnum for Medical Hold
            /// </summary>
            
            MedicalHoldEnum = Medical Hold,
            /// <summary>
            /// Enum PendingIntakeTestingEnum for Pending Intake Testing
            /// </summary>
            
            PendingIntakeTestingEnum = Pending Intake Testing        }
}
