/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets CountyMI
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CountyMI
        {
            /// <summary>
            /// Enum AlconaEnum for Alcona
            /// </summary>
            [EnumMember(Value = "Alcona")]
            AlconaEnum = 0,
            /// <summary>
            /// Enum AlgerEnum for Alger
            /// </summary>
            [EnumMember(Value = "Alger")]
            AlgerEnum = 1,
            /// <summary>
            /// Enum AlleganEnum for Allegan
            /// </summary>
            [EnumMember(Value = "Allegan")]
            AlleganEnum = 2,
            /// <summary>
            /// Enum AlpenaEnum for Alpena
            /// </summary>
            [EnumMember(Value = "Alpena")]
            AlpenaEnum = 3,
            /// <summary>
            /// Enum AntrimEnum for Antrim
            /// </summary>
            [EnumMember(Value = "Antrim")]
            AntrimEnum = 4,
            /// <summary>
            /// Enum ArenacEnum for Arenac
            /// </summary>
            [EnumMember(Value = "Arenac")]
            ArenacEnum = 5,
            /// <summary>
            /// Enum BaragaEnum for Baraga
            /// </summary>
            [EnumMember(Value = "Baraga")]
            BaragaEnum = 6,
            /// <summary>
            /// Enum BarryEnum for Barry
            /// </summary>
            [EnumMember(Value = "Barry")]
            BarryEnum = 7,
            /// <summary>
            /// Enum BayEnum for Bay
            /// </summary>
            [EnumMember(Value = "Bay")]
            BayEnum = 8,
            /// <summary>
            /// Enum BenzieEnum for Benzie
            /// </summary>
            [EnumMember(Value = "Benzie")]
            BenzieEnum = 9,
            /// <summary>
            /// Enum BerrienEnum for Berrien
            /// </summary>
            [EnumMember(Value = "Berrien")]
            BerrienEnum = 10,
            /// <summary>
            /// Enum BranchEnum for Branch
            /// </summary>
            [EnumMember(Value = "Branch")]
            BranchEnum = 11,
            /// <summary>
            /// Enum CalhounEnum for Calhoun
            /// </summary>
            [EnumMember(Value = "Calhoun")]
            CalhounEnum = 12,
            /// <summary>
            /// Enum CassEnum for Cass
            /// </summary>
            [EnumMember(Value = "Cass")]
            CassEnum = 13,
            /// <summary>
            /// Enum CharlevoixEnum for Charlevoix
            /// </summary>
            [EnumMember(Value = "Charlevoix")]
            CharlevoixEnum = 14,
            /// <summary>
            /// Enum CheboyganEnum for Cheboygan
            /// </summary>
            [EnumMember(Value = "Cheboygan")]
            CheboyganEnum = 15,
            /// <summary>
            /// Enum ChippewaEnum for Chippewa
            /// </summary>
            [EnumMember(Value = "Chippewa")]
            ChippewaEnum = 16,
            /// <summary>
            /// Enum ClareEnum for Clare
            /// </summary>
            [EnumMember(Value = "Clare")]
            ClareEnum = 17,
            /// <summary>
            /// Enum ClintonEnum for Clinton
            /// </summary>
            [EnumMember(Value = "Clinton")]
            ClintonEnum = 18,
            /// <summary>
            /// Enum CrawfordEnum for Crawford
            /// </summary>
            [EnumMember(Value = "Crawford")]
            CrawfordEnum = 19,
            /// <summary>
            /// Enum DeltaEnum for Delta
            /// </summary>
            [EnumMember(Value = "Delta")]
            DeltaEnum = 20,
            /// <summary>
            /// Enum DickinsonEnum for Dickinson
            /// </summary>
            [EnumMember(Value = "Dickinson")]
            DickinsonEnum = 21,
            /// <summary>
            /// Enum EatonEnum for Eaton
            /// </summary>
            [EnumMember(Value = "Eaton")]
            EatonEnum = 22,
            /// <summary>
            /// Enum EmmetEnum for Emmet
            /// </summary>
            [EnumMember(Value = "Emmet")]
            EmmetEnum = 23,
            /// <summary>
            /// Enum GeneseeEnum for Genesee
            /// </summary>
            [EnumMember(Value = "Genesee")]
            GeneseeEnum = 24,
            /// <summary>
            /// Enum GladwinEnum for Gladwin
            /// </summary>
            [EnumMember(Value = "Gladwin")]
            GladwinEnum = 25,
            /// <summary>
            /// Enum GogebicEnum for Gogebic
            /// </summary>
            [EnumMember(Value = "Gogebic")]
            GogebicEnum = 26,
            /// <summary>
            /// Enum GrandTraverseEnum for Grand Traverse
            /// </summary>
            [EnumMember(Value = "Grand Traverse")]
            GrandTraverseEnum = 27,
            /// <summary>
            /// Enum GratiotEnum for Gratiot
            /// </summary>
            [EnumMember(Value = "Gratiot")]
            GratiotEnum = 28,
            /// <summary>
            /// Enum HillsdaleEnum for Hillsdale
            /// </summary>
            [EnumMember(Value = "Hillsdale")]
            HillsdaleEnum = 29,
            /// <summary>
            /// Enum HoughtonEnum for Houghton
            /// </summary>
            [EnumMember(Value = "Houghton")]
            HoughtonEnum = 30,
            /// <summary>
            /// Enum HuronEnum for Huron
            /// </summary>
            [EnumMember(Value = "Huron")]
            HuronEnum = 31,
            /// <summary>
            /// Enum InghamEnum for Ingham
            /// </summary>
            [EnumMember(Value = "Ingham")]
            InghamEnum = 32,
            /// <summary>
            /// Enum IoniaEnum for Ionia
            /// </summary>
            [EnumMember(Value = "Ionia")]
            IoniaEnum = 33,
            /// <summary>
            /// Enum IoscoEnum for Iosco
            /// </summary>
            [EnumMember(Value = "Iosco")]
            IoscoEnum = 34,
            /// <summary>
            /// Enum IronEnum for Iron
            /// </summary>
            [EnumMember(Value = "Iron")]
            IronEnum = 35,
            /// <summary>
            /// Enum IsabellaEnum for Isabella
            /// </summary>
            [EnumMember(Value = "Isabella")]
            IsabellaEnum = 36,
            /// <summary>
            /// Enum JacksonEnum for Jackson
            /// </summary>
            [EnumMember(Value = "Jackson")]
            JacksonEnum = 37,
            /// <summary>
            /// Enum KalamazooEnum for Kalamazoo
            /// </summary>
            [EnumMember(Value = "Kalamazoo")]
            KalamazooEnum = 38,
            /// <summary>
            /// Enum KalkaskaEnum for Kalkaska
            /// </summary>
            [EnumMember(Value = "Kalkaska")]
            KalkaskaEnum = 39,
            /// <summary>
            /// Enum KentEnum for Kent
            /// </summary>
            [EnumMember(Value = "Kent")]
            KentEnum = 40,
            /// <summary>
            /// Enum KeweenawEnum for Keweenaw
            /// </summary>
            [EnumMember(Value = "Keweenaw")]
            KeweenawEnum = 41,
            /// <summary>
            /// Enum LakeEnum for Lake
            /// </summary>
            [EnumMember(Value = "Lake")]
            LakeEnum = 42,
            /// <summary>
            /// Enum LapeerEnum for Lapeer
            /// </summary>
            [EnumMember(Value = "Lapeer")]
            LapeerEnum = 43,
            /// <summary>
            /// Enum LeelanauEnum for Leelanau
            /// </summary>
            [EnumMember(Value = "Leelanau")]
            LeelanauEnum = 44,
            /// <summary>
            /// Enum LenaweeEnum for Lenawee
            /// </summary>
            [EnumMember(Value = "Lenawee")]
            LenaweeEnum = 45,
            /// <summary>
            /// Enum LivingstonEnum for Livingston
            /// </summary>
            [EnumMember(Value = "Livingston")]
            LivingstonEnum = 46,
            /// <summary>
            /// Enum LuceEnum for Luce
            /// </summary>
            [EnumMember(Value = "Luce")]
            LuceEnum = 47,
            /// <summary>
            /// Enum MackinacEnum for Mackinac
            /// </summary>
            [EnumMember(Value = "Mackinac")]
            MackinacEnum = 48,
            /// <summary>
            /// Enum MacombEnum for Macomb
            /// </summary>
            [EnumMember(Value = "Macomb")]
            MacombEnum = 49,
            /// <summary>
            /// Enum ManisteeEnum for Manistee
            /// </summary>
            [EnumMember(Value = "Manistee")]
            ManisteeEnum = 50,
            /// <summary>
            /// Enum MarquetteEnum for Marquette
            /// </summary>
            [EnumMember(Value = "Marquette")]
            MarquetteEnum = 51,
            /// <summary>
            /// Enum MasonEnum for Mason
            /// </summary>
            [EnumMember(Value = "Mason")]
            MasonEnum = 52,
            /// <summary>
            /// Enum MecostaEnum for Mecosta
            /// </summary>
            [EnumMember(Value = "Mecosta")]
            MecostaEnum = 53,
            /// <summary>
            /// Enum MenomineeEnum for Menominee
            /// </summary>
            [EnumMember(Value = "Menominee")]
            MenomineeEnum = 54,
            /// <summary>
            /// Enum MidlandEnum for Midland
            /// </summary>
            [EnumMember(Value = "Midland")]
            MidlandEnum = 55,
            /// <summary>
            /// Enum MissaukeeEnum for Missaukee
            /// </summary>
            [EnumMember(Value = "Missaukee")]
            MissaukeeEnum = 56,
            /// <summary>
            /// Enum MonroeEnum for Monroe
            /// </summary>
            [EnumMember(Value = "Monroe")]
            MonroeEnum = 57,
            /// <summary>
            /// Enum MontcalmEnum for Montcalm
            /// </summary>
            [EnumMember(Value = "Montcalm")]
            MontcalmEnum = 58,
            /// <summary>
            /// Enum MontmorencyEnum for Montmorency
            /// </summary>
            [EnumMember(Value = "Montmorency")]
            MontmorencyEnum = 59,
            /// <summary>
            /// Enum MuskegonEnum for Muskegon
            /// </summary>
            [EnumMember(Value = "Muskegon")]
            MuskegonEnum = 60,
            /// <summary>
            /// Enum NewaygoEnum for Newaygo
            /// </summary>
            [EnumMember(Value = "Newaygo")]
            NewaygoEnum = 61,
            /// <summary>
            /// Enum OaklandEnum for Oakland
            /// </summary>
            [EnumMember(Value = "Oakland")]
            OaklandEnum = 62,
            /// <summary>
            /// Enum OceanaEnum for Oceana
            /// </summary>
            [EnumMember(Value = "Oceana")]
            OceanaEnum = 63,
            /// <summary>
            /// Enum OgemawEnum for Ogemaw
            /// </summary>
            [EnumMember(Value = "Ogemaw")]
            OgemawEnum = 64,
            /// <summary>
            /// Enum OntonagonEnum for Ontonagon
            /// </summary>
            [EnumMember(Value = "Ontonagon")]
            OntonagonEnum = 65,
            /// <summary>
            /// Enum OsceolaEnum for Osceola
            /// </summary>
            [EnumMember(Value = "Osceola")]
            OsceolaEnum = 66,
            /// <summary>
            /// Enum OscodaEnum for Oscoda
            /// </summary>
            [EnumMember(Value = "Oscoda")]
            OscodaEnum = 67,
            /// <summary>
            /// Enum OtsegoEnum for Otsego
            /// </summary>
            [EnumMember(Value = "Otsego")]
            OtsegoEnum = 68,
            /// <summary>
            /// Enum OttawaEnum for Ottawa
            /// </summary>
            [EnumMember(Value = "Ottawa")]
            OttawaEnum = 69,
            /// <summary>
            /// Enum PresqueIsleEnum for Presque Isle
            /// </summary>
            [EnumMember(Value = "Presque Isle")]
            PresqueIsleEnum = 70,
            /// <summary>
            /// Enum RoscommonEnum for Roscommon
            /// </summary>
            [EnumMember(Value = "Roscommon")]
            RoscommonEnum = 71,
            /// <summary>
            /// Enum SaginawEnum for Saginaw
            /// </summary>
            [EnumMember(Value = "Saginaw")]
            SaginawEnum = 72,
            /// <summary>
            /// Enum StClairEnum for St. Clair
            /// </summary>
            [EnumMember(Value = "St. Clair")]
            StClairEnum = 73,
            /// <summary>
            /// Enum StJosephEnum for St. Joseph
            /// </summary>
            [EnumMember(Value = "St. Joseph")]
            StJosephEnum = 74,
            /// <summary>
            /// Enum SanilacEnum for Sanilac
            /// </summary>
            [EnumMember(Value = "Sanilac")]
            SanilacEnum = 75,
            /// <summary>
            /// Enum SchoolcraftEnum for Schoolcraft
            /// </summary>
            [EnumMember(Value = "Schoolcraft")]
            SchoolcraftEnum = 76,
            /// <summary>
            /// Enum ShiawasseeEnum for Shiawassee
            /// </summary>
            [EnumMember(Value = "Shiawassee")]
            ShiawasseeEnum = 77,
            /// <summary>
            /// Enum TuscolaEnum for Tuscola
            /// </summary>
            [EnumMember(Value = "Tuscola")]
            TuscolaEnum = 78,
            /// <summary>
            /// Enum VanBurenEnum for Van Buren
            /// </summary>
            [EnumMember(Value = "Van Buren")]
            VanBurenEnum = 79,
            /// <summary>
            /// Enum WashtenawEnum for Washtenaw
            /// </summary>
            [EnumMember(Value = "Washtenaw")]
            WashtenawEnum = 80,
            /// <summary>
            /// Enum WayneEnum for Wayne
            /// </summary>
            [EnumMember(Value = "Wayne")]
            WayneEnum = 81,
            /// <summary>
            /// Enum WexfordEnum for Wexford
            /// </summary>
            [EnumMember(Value = "Wexford")]
            WexfordEnum = 82        }
}
