/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Intake : IEquatable<Intake>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id")]
        public Id Id { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [Required]
        [DataMember(Name="timestamp")]
        public string Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets StaffId
        /// </summary>
        [Required]
        [DataMember(Name="staffId")]
        public Guid? StaffId { get; set; }

        /// <summary>
        /// Gets or Sets ParNumber
        /// </summary>
        [Required]
        [DataMember(Name="parNumber")]
        public int? ParNumber { get; set; }

        /// <summary>
        /// Gets or Sets SurrenderingPartyId
        /// </summary>
        [DataMember(Name="surrenderingPartyId")]
        public Guid? SurrenderingPartyId { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name="notes")]
        public List<Note> Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Intake {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  StaffId: ").Append(StaffId).Append("\n");
            sb.Append("  ParNumber: ").Append(ParNumber).Append("\n");
            sb.Append("  SurrenderingPartyId: ").Append(SurrenderingPartyId).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Intake)obj);
        }

        /// <summary>
        /// Returns true if Intake instances are equal
        /// </summary>
        /// <param name="other">Instance of Intake to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Intake other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Timestamp == other.Timestamp ||
                    Timestamp != null &&
                    Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    StaffId == other.StaffId ||
                    StaffId != null &&
                    StaffId.Equals(other.StaffId)
                ) && 
                (
                    ParNumber == other.ParNumber ||
                    ParNumber != null &&
                    ParNumber.Equals(other.ParNumber)
                ) && 
                (
                    SurrenderingPartyId == other.SurrenderingPartyId ||
                    SurrenderingPartyId != null &&
                    SurrenderingPartyId.Equals(other.SurrenderingPartyId)
                ) && 
                (
                    Notes == other.Notes ||
                    Notes != null &&
                    Notes.SequenceEqual(other.Notes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Timestamp != null)
                    hashCode = hashCode * 59 + Timestamp.GetHashCode();
                    if (StaffId != null)
                    hashCode = hashCode * 59 + StaffId.GetHashCode();
                    if (ParNumber != null)
                    hashCode = hashCode * 59 + ParNumber.GetHashCode();
                    if (SurrenderingPartyId != null)
                    hashCode = hashCode * 59 + SurrenderingPartyId.GetHashCode();
                    if (Notes != null)
                    hashCode = hashCode * 59 + Notes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Intake left, Intake right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Intake left, Intake right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
