/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets MedicalEventType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MedicalEventType
        {
            /// <summary>
            /// Enum VaccinationEnum for Vaccination
            /// </summary>
            [EnumMember(Value = "Vaccination")]
            VaccinationEnum = 0,
            /// <summary>
            /// Enum PreventativeEnum for Preventative
            /// </summary>
            [EnumMember(Value = "Preventative")]
            PreventativeEnum = 1,
            /// <summary>
            /// Enum SurgeryEnum for Surgery
            /// </summary>
            [EnumMember(Value = "Surgery")]
            SurgeryEnum = 2        }
}
