/*
 * AnimalRescue API
 *
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets Species
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum Species
        {
            /// <summary>
            /// Enum DogEnum for Dog
            /// </summary>
            [EnumMember(Value = "Dog")]
            DogEnum = 0,
            /// <summary>
            /// Enum CatEnum for Cat
            /// </summary>
            [EnumMember(Value = "Cat")]
            CatEnum = 1        }
}
